#服务器端口
server:
  port: 8082

#上传图片大小
spring:
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb

#Redis配置
spring:
  redis:
    database: 0      # Redis数据库索引（默认为0）
    host: 192.168.1.3  # Redis服务器地址
    port: 6379       # Redis服务器连接端口
    password:        # Redis服务器连接密码（默认为空）
    timeout: 0       # 连接超时时间（毫秒）
    pool:
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 8    # 连接池中的最大空闲连接
      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0    # 连接池中的最小空闲连接